// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ4E7nk0jys9sXka7j7R2Zn4DbkD2F29M',
    appId: '1:561369727802:web:d4817ddde8e56499e74603',
    messagingSenderId: '561369727802',
    projectId: 'buskahanhay',
    authDomain: 'buskahanhay.firebaseapp.com',
    storageBucket: 'buskahanhay.firebasestorage.app',
    measurementId: 'G-LZNE88J95R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5WTtRPHHmuIJ-1xfdmbH42AYOSXLr7ic',
    appId: '1:561369727802:android:8ab42400fb89470ee74603',
    messagingSenderId: '561369727802',
    projectId: 'buskahanhay',
    storageBucket: 'buskahanhay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANSwU2cjH-mQQd2tdo2nxTjcKDKolrUK4',
    appId: '1:561369727802:ios:6cf1e92ae38f7c8be74603',
    messagingSenderId: '561369727802',
    projectId: 'buskahanhay',
    storageBucket: 'buskahanhay.firebasestorage.app',
    iosBundleId: 'com.example.busKahanHay',
  );
}
